language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.8"

# npm update needed to get a version compatible with
# new semver conventions (usage of the caret "^" instead of "~" to
# specify dependencies' version) when Travis uses node 0.8.
before_install:
  - npm update -g npm
